providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311Full",
  "postgresql",
  "gcc"
]

[phases.release]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py shell < manage_superuser.py"


[start]
cmd = "honcho start"