providers = ["python"]

[phases.setup]
nixPkgs = ["postgresql", "gcc"]

[phases.install]
cmds = ["python -m pip install --upgrade pip"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --no-input"
]

[start]
cmd = "gunicorn perfume_shop.wsgi:application"
startupCommand = ["python manage.py migrate"]

[start.env]
PORT = "8000"
PYTHONUNBUFFERED = "1"