providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311Full",
  "postgresql",
  "gcc"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate --noinput && honcho start"
