providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311Full",
  "postgresql",
  "gcc"
]

[phases.build]
cmds = [
  "adduser -D appuser",
  "chown -R appuser /app"
]

[start]
cmd = "su appuser -c 'honcho start'"