providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311Full",
  "postgresql",
  "gcc"
]

[phases.release]
# Runs only once per deployment
cmd = """
  python manage.py migrate --noinput &&
  python manage.py shell < manage_superuser.py
"""

[start]
cmd = "honcho start"